// SPDX-FileCopyrightText: 2026 Ivar
// SPDX-License-Identifier: GPL-3.0-or-later
//
// The drawer's own settings page (right-click the arrow, Configure). It works without Tidy
// running. Tidy's Panel tab has the same settings, plus the place of the arrow.
// Generated by plasma-tidy; edit it there.

import QtQuick
import QtQuick.Controls as QQC2
import QtQuick.Layouts
import org.kde.kirigami as Kirigami
import org.kde.kcmutils as KCM
import org.kde.plasma.plasmoid

KCM.SimpleKCM {
    id: page

    // Only the settings that are edited here: Plasma writes every cfg_ property back, and
    // the drawer's state (closed, what it holds for a task manager) must not be among them.
    property string cfg_name
    property var cfg_targets: []
    property string cfg_taskMode
    property string cfg_openOn
    property int cfg_hoverDelay
    property bool cfg_autoClose
    property string cfg_closeScope
    property int cfg_closeDelay
    property bool cfg_closeOnPanelClick
    property bool cfg_openOnPanelClick
    property bool cfg_closeAfterUse
    property bool cfg_closeOnMaximized
    property bool cfg_openOnDesktop
    property bool cfg_openOnAttention
    property string cfg_animation
    property string cfg_display
    property string cfg_popupStyle
    property bool cfg_popupBackground
    property bool cfg_popupGap
    property string cfg_trayArrow
    property int cfg_animationDuration
    property string cfg_activePlace
    property bool cfg_reverseArrow
    property string cfg_indicator
    property string cfg_icon
    property string cfg_iconCustom

    // Texts come from Tidy, in the language it is set to.
    readonly property var texts: {
        try { return JSON.parse(Plasmoid.configuration.uiTexts || "{}"); } catch (e) { return {}; }
    }
    function t(s) { return texts[s] || s; }

    readonly property var skipped: ["org.kde.plasma.marginsseparator", "org.kde.plasma.panelspacer"]
    readonly property var others: {
        var list = [];
        try {
            var all = Plasmoid.containment.applets;
            for (var i = 0; i < all.length; i++) {
                var a = all[i];
                if (a === Plasmoid || a.pluginName === Plasmoid.pluginName
                        || skipped.indexOf(a.pluginName) >= 0) continue;
                list.push({id: String(a.id), title: a.title, plugin: a.pluginName});
            }
        } catch (e) {}
        return list;
    }
    function isTarget(id) { return Array.from(cfg_targets).indexOf(id) >= 0; }
    function setTarget(id, on) {
        var list = Array.from(cfg_targets).filter(x => x !== id);
        if (on) list.push(id);
        cfg_targets = list;
    }
    readonly property bool hasTasks: others.some(
        o => isTarget(o.id) && (o.plugin === "org.kde.plasma.icontasks" || o.plugin === "org.kde.plasma.taskmanager"))

    component Choice: QQC2.ComboBox {
        property var choices: []        // [[value, text], ...]
        property string value
        signal chosen(string value)
        model: choices.map(c => page.t(c[1]))
        currentIndex: Math.max(0, choices.findIndex(c => c[0] === value))
        onActivated: index => chosen(choices[index][0])
    }

    Kirigami.FormLayout {
        QQC2.TextField {
            Kirigami.FormData.label: page.t("Name:")
            text: page.cfg_name
            onTextEdited: page.cfg_name = text
        }

        // --- contents ---
        Item { Kirigami.FormData.isSection: true; Kirigami.FormData.label: page.t("In this drawer") }
        Repeater {
            model: page.others
            QQC2.CheckBox {
                required property var modelData
                text: modelData.title
                checked: page.isTarget(modelData.id)
                onToggled: page.setTarget(modelData.id, checked)
            }
        }
        Choice {
            Kirigami.FormData.label: page.t("Task manager:")
            enabled: page.hasTasks
            choices: [["all", "Hide all programs, open ones too"],
                      ["pinned", "Hide only pinned programs that are not open"]]
            value: page.cfg_taskMode
            onChosen: value => page.cfg_taskMode = value
        }
        Choice {
            Kirigami.FormData.label: page.t("Open programs:")
            enabled: page.hasTasks
            choices: [["fixed", "On their pinned spot"], ["start", "All in front"],
                      ["end", "All at the back"]]
            value: page.cfg_activePlace
            onChosen: value => page.cfg_activePlace = value
        }

        // --- opening and closing ---
        Item { Kirigami.FormData.isSection: true; Kirigami.FormData.label: page.t("Opening and closing") }
        Choice {
            Kirigami.FormData.label: page.t("Open with:")
            choices: [["click", "A click on the arrow"], ["hover", "Pointing at the arrow (a click works too)"]]
            value: page.cfg_openOn
            onChosen: value => page.cfg_openOn = value
        }
        QQC2.SpinBox {
            Kirigami.FormData.label: page.t("Pointing opens after:")
            enabled: page.cfg_openOn === "hover"
            from: 0; to: 3000; stepSize: 50
            value: page.cfg_hoverDelay
            textFromValue: value => value + " ms"
            valueFromText: text => parseInt(text) || 0
            onValueModified: page.cfg_hoverDelay = value
        }
        QQC2.CheckBox {
            text: page.t("Open when a program asks for attention")
            checked: page.cfg_openOnAttention
            onToggled: page.cfg_openOnAttention = checked
        }
        QQC2.CheckBox {
            text: page.t("Open with a click on an empty spot in the panel")
            checked: page.cfg_openOnPanelClick
            onToggled: page.cfg_openOnPanelClick = checked
        }
        QQC2.CheckBox {
            text: page.t("Open when the desktop is shown")
            checked: page.cfg_openOnDesktop
            onToggled: page.cfg_openOnDesktop = checked
            QQC2.ToolTip.visible: hovered
            QQC2.ToolTip.text: page.t("Works while Tidy is running.")
        }
        Choice {
            Kirigami.FormData.label: page.t("Close by itself:")
            choices: [["", "Never"], ["drawer", "When the pointer leaves the drawer"],
                      ["panel", "When the pointer leaves the panel"]]
            value: page.cfg_autoClose ? page.cfg_closeScope : ""
            onChosen: value => {
                page.cfg_autoClose = value !== "";
                if (value !== "") page.cfg_closeScope = value;
            }
        }
        QQC2.SpinBox {
            Kirigami.FormData.label: page.t("Closes after:")
            enabled: page.cfg_autoClose
            from: 0; to: 600; stepSize: 5     // tenths of a second
            value: Math.round(page.cfg_closeDelay / 100)
            textFromValue: value => (value / 10).toFixed(1) + " s"
            valueFromText: text => Math.round((parseFloat(text.replace(",", ".")) || 0) * 10)
            onValueModified: page.cfg_closeDelay = value * 100
        }
        QQC2.CheckBox {
            text: page.t("Close with a click on an empty spot in the panel")
            checked: page.cfg_closeOnPanelClick
            onToggled: page.cfg_closeOnPanelClick = checked
        }
        QQC2.CheckBox {
            text: page.t("Close after a click on something in the drawer")
            checked: page.cfg_closeAfterUse
            onToggled: page.cfg_closeAfterUse = checked
        }
        QQC2.CheckBox {
            text: page.t("Close when a window that fills the screen comes to the front")
            checked: page.cfg_closeOnMaximized
            onToggled: page.cfg_closeOnMaximized = checked
        }

        // --- arrow ---
        Item { Kirigami.FormData.isSection: true; Kirigami.FormData.label: page.t("Appearance") }
        Choice {
            Kirigami.FormData.label: page.t("Icon:")
            choices: [["arrow", "Arrow"], ["double", "Double arrow"], ["triangle", "Triangle"],
                      ["dots", "Dots"], ["menu", "Menu lines"], ["handle", "Grip"],
                      ["custom", "My own icon"], ["none", "No icon"]]
            value: page.cfg_icon
            onChosen: value => page.cfg_icon = value
        }
        QQC2.TextField {
            visible: page.cfg_icon === "custom"
            Layout.fillWidth: true
            placeholderText: page.t("Icon name or image file")
            text: page.cfg_iconCustom
            onEditingFinished: page.cfg_iconCustom = text
        }
        Choice {
            Kirigami.FormData.label: page.t("Mark on the closed drawer:")
            choices: [["none", "None"], ["open", "A dot when programs are open"],
                      ["count", "The number of open programs"],
                      ["attention", "A dot only when a program asks for attention"]]
            value: page.cfg_indicator
            onChosen: value => page.cfg_indicator = value
        }
        QQC2.CheckBox {
            text: page.t("Arrow points the other way")
            checked: page.cfg_reverseArrow
            onToggled: page.cfg_reverseArrow = checked
        }
        Choice {
            Kirigami.FormData.label: page.t("Shows its contents:")
            choices: [["panel", "In the panel"], ["popup", "In a pop-up above the arrow"]]
            value: page.cfg_display
            onChosen: value => page.cfg_display = value
        }
        Choice {
            Kirigami.FormData.label: page.t("Pop-up:")
            enabled: page.cfg_display === "popup"
            choices: [["row", "A row of icons"], ["column", "A column of icons"],
                      ["grid", "A grid with names"], ["list", "A list with names"]]
            value: page.cfg_popupStyle
            onChosen: value => page.cfg_popupStyle = value
        }
        QQC2.CheckBox {
            text: page.t("Pop-up has a background, like the panel")
            enabled: page.cfg_display === "popup"
            checked: page.cfg_popupBackground
            onToggled: page.cfg_popupBackground = checked
        }
        QQC2.CheckBox {
            text: page.t("Pop-up floats above the panel, like Plasma's own pop-ups")
            enabled: page.cfg_display === "popup"
            checked: page.cfg_popupGap
            onToggled: page.cfg_popupGap = checked
        }
        Choice {
            Kirigami.FormData.label: page.t("The system tray's own arrow (^):")
            enabled: page.cfg_display === "popup"
            choices: [["open", "In the panel while the pop-up is open"], ["always", "Always in the panel"],
                      ["never", "Never"]]
            value: page.cfg_trayArrow
            onChosen: value => page.cfg_trayArrow = value
        }
        Choice {
            Kirigami.FormData.label: page.t("Animation:")
            choices: [["slide", "Slide"], ["grow", "Grow"], ["cascade", "One by one"],
                      ["fade", "Fade"]]
            value: page.cfg_animation
            onChosen: value => page.cfg_animation = value
        }
        QQC2.SpinBox {
            Kirigami.FormData.label: page.t("Speed:")
            from: 50; to: 2000; stepSize: 50
            value: page.cfg_animationDuration
            textFromValue: value => value + " ms"
            valueFromText: text => parseInt(text) || 250
            onValueModified: page.cfg_animationDuration = value
        }
        QQC2.Label {
            Layout.fillWidth: true
            wrapMode: Text.WordWrap
            opacity: 0.7
            text: page.t("The place of the arrow is set in Tidy.")
        }
    }
}
