// SPDX-FileCopyrightText: 2026 Ivar
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Tidy Drawer: an arrow in the panel that tucks neighbouring widgets away.
// Generated by plasma-tidy; edit it there.
//
// Plasma has no public way to hide another widget, so this reaches into the panel's
// layout: every widget sits in an "applet container" next to ours. Nothing is written
// to those widgets (except the pinned list of a task manager in "pinned" mode); if a
// Plasma update changes the layout, the drawer simply stops hiding things.

import QtQuick
import QtQuick.Layouts
import org.kde.plasma.plasmoid
import org.kde.plasma.core as PlasmaCore
import org.kde.plasma.plasma5support as P5Support
import org.kde.kirigami as Kirigami
import org.kde.taskmanager as TaskManager

PlasmoidItem {
    id: root

    readonly property var cfg: Plasmoid.configuration
    readonly property bool vertical: Plasmoid.formFactor === PlasmaCore.Types.Vertical
    // While the panel is being edited everything must stay reachable.
    readonly property bool editing: (Plasmoid.containment?.corona?.editMode ?? false)
                                    || (Plasmoid.containment?.userConfiguring ?? false)
    // Removed from the panel (Plasma keeps a removed widget alive for a while, for "undo"):
    // let go of everything.
    property bool leaving: false
    Connections {
        target: Plasmoid
        function onDestroyedChanged(destroyed) {
            root.leaving = destroyed;
            root.syncPinned();
            root.syncFill();
        }
    }
    // Paused (Tidy's "Restore everything"): the drawer lets go of everything, as if it were
    // not there, until Tidy is switched on again or the arrow is clicked.
    // Peek (Tidy's key to hold): open for as long as the key is held, whatever else is set.
    readonly property bool wantClosed: cfg.closed && !editing && !leaving && !cfg.paused && !peeking

    // --- what Tidy tells -------------------------------------------------------------------

    // Tidy tells two things with a signal on the session bus: that a peek starts or ends,
    // and that the desktop came to the front. The link is made by hand, so that a Plasma
    // without this module leaves the drawer working; it then only misses these two.
    property bool peeking: false
    property var tidyLink: null
    function linkTidy() {
        try {
            tidyLink = Qt.createQmlObject('import QtQuick; import org.kde.plasma.workspace.dbus as DBus; '
                + 'QtObject { id: link; property string name: "io.github.wispware.PlasmaTidy"; '
                + 'property bool runs: watch.registered; signal peek(bool on); signal desktop(); '
                + 'property var watch: DBus.DBusServiceWatcher { busType: DBus.BusType.Session; '
                + 'watchedService: link.name } '
                + 'property var listen: DBus.SignalWatcher { busType: DBus.BusType.Session; '
                + 'service: link.name; path: "/"; iface: link.name; '
                + 'function dbusPeeking(on) { link.peek(on === true || String(on) === "true"); } '
                + 'function dbusDesktopActivated() { link.desktop(); } } }', root, "tidyLink");
            tidyLink.peek.connect(on => { root.peeking = on; });
            // Tidy gone in the middle of a peek: it is over.
            tidyLink.runsChanged.connect(() => { if (!tidyLink.runs) root.peeking = false; });
            tidyLink.desktop.connect(() => {
                if (root.cfg.openOnDesktop && root.cfg.closed && !root.cfg.paused)
                    root.cfg.closed = false;
            });
        } catch (e) {
            console.warn("TIDYDRAWER cannot hear Tidy: " + e);
        }
    }

    property Item container: null   // our own applet container
    property var siblings: []       // the other widgets: [{item, id, plugin, pos}]
    property int ownPos: -1

    function isTasks(plugin) {
        return plugin === "org.kde.plasma.icontasks" || plugin === "org.kde.plasma.taskmanager";
    }
    function inTargets(id) {
        return Array.from(cfg.targets).indexOf(id) >= 0;
    }

    // Widgets hidden as a whole, and task managers, whose icons are hidden one by one.
    readonly property var wholeTargets: siblings.filter(s => inTargets(s.id) && !isTasks(s.plugin))
    readonly property var taskManagers: siblings.filter(s => inTargets(s.id) && isTasks(s.plugin))
    // Sliding makes things narrower until they are gone. Fading and one-by-one leave an
    // icon at its normal size and only change how see-through it is; a whole widget (the
    // system tray, the clock) still slides in one-by-one, as it is one thing.
    readonly property bool shrinks: cfg.animation === "grow"
    // "slide" (also for a style this version doesn't know): the icons keep their size and
    // slide out from under the arrow together, like a drawer.
    readonly property bool slides: !shrinks && cfg.animation !== "fade" && cfg.animation !== "cascade"
    readonly property bool widgetsShrink: cfg.animation !== "fade"
    // How long the task manager takes to move an icon aside.
    readonly property int moveTime: Kirigami.Units.longDuration
    function scan() {
        var c = root.parent, hops = 0;
        while (c && !c.isAppletContainer && hops < 8) { c = c.parent; hops++; }
        if (!c || !c.isAppletContainer || !c.parent) {
            container = null;
            siblings = [];
            return;
        }
        container = c;
        ownPos = c.index;
        var list = [], kids = c.parent.children;
        for (var i = 0; i < kids.length; i++) {
            var k = kids[i];
            if (!k || k === c || !k.isAppletContainer || !k.applet) continue;
            var applet = null;
            try { applet = k.applet.plasmoid; } catch (e) {}
            if (!applet) continue;
            list.push({item: k, id: String(applet.id), plugin: applet.pluginName, pos: k.index,
                       tray: trayStateOf(k.applet, applet.pluginName)});
        }
        // Only replace the list when it really changed: replacing it rebuilds the hiders.
        var key = l => l.map(s => s.id + "@" + s.pos + (s.tray ? "t" : "")).join(",");
        // The system tray builds its inside a little later: look again a few times.
        if (trayTries < 5 && list.some(s => s.plugin === "org.kde.plasma.systemtray" && !s.tray)) {
            trayTries++;
            trayRetry.restart();
        }
        if (key(list) !== key(siblings) || list.some((s, i) => s.item !== siblings[i].item))
            siblings = list;
        syncPinned();
        syncFill();
    }

    // Diagnostics: with the "debug" setting on "on", the state goes to the journal twice a second.
    function report() {
        polishTasks();
        console.warn("TIDYDRAWER " + JSON.stringify({
            own: ownPos, closed: cfg.closed, paused: cfg.paused, mode: cfg.taskMode,
            hover: panelHover !== null,
            width: Math.round(root.width), stretching: stretching, savedFill: cfg.savedFill,
            arrow_icon: arrowIcon, windows: hiddenWindows, attention: hiddenAttention,
            trays: siblings.filter(s => s.tray).length, popup_open: popupOpen,
            mark: markShown,
            inPanel: pointerInPanel, inDrawer: pointerInDrawer, arrow: arrowHovered,
            popup: popupOpen, saved: cfg.savedLaunchers, tap: panelTap !== null,
            memory: JSON.stringify(savedMemory),
            // is the middle of each widget's contents an empty spot, and the middle of the rest of it?
            spots: siblings.map(s => {
                var start = vertical ? s.item.y : s.item.x, full = vertical ? s.item.height : s.item.width;
                var extent = contentExtent(s.item);
                return s.plugin.replace("org.kde.plasma.", "") + ":" + isEmptySpot(start + extent / 2)
                    + (extent < full ? "/" + isEmptySpot(start + extent + (full - extent) / 2) : "");
            }),
            siblings: siblings.map(s => s.plugin.replace("org.kde.plasma.", "") + "#" + s.id + "@" + s.pos
                                        + (s.item.visible ? "" : "/hidden") + "/o" + s.item.opacity
                                        + "/w" + Math.round(s.item.width)
                                        + (isTasks(s.plugin) ? "/L" + Array.from(s.item.applet.plasmoid.configuration.launchers).length : "")),
            whole: wholeTargets.map(s => s.id),
            tasks: taskHiders.slice().sort((a, b) => (vertical ? a.item.y - b.item.y : a.item.x - b.item.x)).map(h => {
                var m = h.item.model;
                return (m.IsLauncher ? "L" : "W") + ":" + String(m.AppName || m.display).slice(0, 10)
                    + "#" + m.AppId + (h.hider.kept ? "/kept" : "")
                    + "@" + Math.round(vertical ? h.item.y : h.item.x)
                    + "/w" + Math.round(vertical ? h.item.height : h.item.width)
                    + "/f" + h.hider.factor.toFixed(2) + (h.item.visible ? "" : "/hidden");
            }),
            tasksMoving: tasksMoving}));
    }
    Timer { interval: 500; repeat: true; running: root.cfg.debug === "on"; onTriggered: root.report() }
    // ...and while the icons of a task manager move, where they are, frame by frame.
    property var trace: []
    // Layouts are worked out when a frame is drawn; behind a lock screen none is. For the
    // diagnostics, have them worked out now.
    function polishTasks() {
        try {
            if (taskHiders.length) taskHiders[0].item.parent.ensurePolished();
            if (container) container.parent.ensurePolished();
        } catch (e) {}
        return false;
    }
    Timer {
        interval: 16; repeat: true
        running: root.cfg.debug === "on" && (root.tasksMoving || root.slideActive)
        onTriggered: root.polishTasks() || root.trace.push(root.taskHiders.slice()
            .sort((a, b) => (root.vertical ? a.item.y - b.item.y : a.item.x - b.item.x))
            .map(h => Math.round(root.vertical ? h.item.y : h.item.x) + ":" + Math.round(h.item.width)
                      + ":" + (h.item.visible ? h.item.opacity.toFixed(2) : "--")
                      + ":" + Math.round(h.item.transform[0] ? h.item.transform[0].x : 0)).join(" "))
        onRunningChanged: {
            if (running) { root.trace = []; return; }
            console.warn("TIDYTRACE " + JSON.stringify(root.trace));
        }
    }

    Timer { id: rescan; interval: 300; onTriggered: root.scan() }
    Timer { id: trayRetry; interval: 2500; onTriggered: root.scan() }
    property int trayTries: 0
    // The system tray shows a pop-up of its own; whether it is open is kept in an object
    // inside it.
    function trayStateOf(item, plugin) {
        if (plugin !== "org.kde.plasma.systemtray" || !item) return null;
        var level = [item];
        for (var depth = 0; depth < 5 && level.length; depth++) {
            var next = [];
            for (var i = 0; i < level.length; i++) {
                var c = level[i];
                if (c && c.systemTrayState !== undefined && c.systemTrayState) return c.systemTrayState;
                if (c && c.children) for (var j = 0; j < c.children.length; j++) next.push(c.children[j]);
            }
            level = next;
        }
        return null;
    }
    onParentChanged: rescan.restart()
    Component.onCompleted: { rescan.restart(); linkTidy(); }
    Connections {
        target: root.container ? root.container.parent : null
        function onChildrenChanged() { rescan.restart(); }
    }
    Connections {
        target: root.container
        function onIndexChanged() { rescan.restart(); }
    }

    // --- hiding whole widgets ------------------------------------------------

    Instantiator {
        id: hiders
        model: root.wholeTargets
        delegate: QtObject {
            id: h
            required property var modelData
            readonly property Item item: modelData ? modelData.item : null
            readonly property bool after: modelData ? modelData.pos > root.ownPos : true
            // A widget that fills the panel (usually the task manager) keeps its place when
            // closed, so the rest of the panel doesn't jump; the others give up their space.
            readonly property bool fills: item ? (root.vertical ? item.wantsToFillHeight : item.wantsToFillWidth) : false
            property real size: 0   // natural size, remembered while open
            property real factor: root.wantClosed ? 0 : 1
            property bool ready: false
            readonly property real slide: Math.min(size, Kirigami.Units.gridUnit * 14) * (1 - factor)
            readonly property bool moving: factor > 0 && factor < 1

            function measure() {
                if (item && factor === 1) size = root.vertical ? item.height : item.width;
            }
            Component.onCompleted: { measure(); ready = true; }
            // A hider that goes while it is hiding (settings changed, drawer removed) must put
            // its widget back first: the bindings below only restore while they still exist.
            function release() { ready = false; factor = 1; }
            Component.onDestruction: release()
            onFactorChanged: measure()
            property Connections sizes: Connections {
                target: h.item
                function onWidthChanged() { h.measure(); }
                function onHeightChanged() { h.measure(); }
            }

            Behavior on factor {
                enabled: h.ready && root.cfg.animation !== "none" && !root.leaving
                NumberAnimation { duration: root.cfg.animationDuration; easing.type: Easing.InOutCubic }
            }

            property Binding b1: Binding {
                target: h.item; property: "visible"; value: false
                when: h.factor === 0 && !h.fills
                restoreMode: Binding.RestoreBinding
            }
            property Binding b2: Binding {
                target: h.item; property: "opacity"; value: h.factor
                when: h.factor < 1
                restoreMode: Binding.RestoreBindingOrValue
            }
            property Binding b3: Binding {
                target: h.item; property: "enabled"; value: false
                when: h.factor < 1
                restoreMode: Binding.RestoreBindingOrValue
            }
            property Binding b4: Binding {
                target: h.item; property: "clip"; value: true
                when: h.factor < 1
                restoreMode: Binding.RestoreBindingOrValue
            }
            // The contents slide towards the arrow...
            property Binding b5: Binding {
                target: h.item && h.item.applet ? h.item.applet.anchors : null
                property: root.vertical ? (h.after ? "topMargin" : "bottomMargin")
                                        : (h.after ? "leftMargin" : "rightMargin")
                value: -h.slide
                when: h.moving && h.size > 0 && root.widgetsShrink
                restoreMode: Binding.RestoreBindingOrValue
            }
            property Binding b6: Binding {
                target: h.item && h.item.applet ? h.item.applet.anchors : null
                property: root.vertical ? (h.after ? "bottomMargin" : "topMargin")
                                        : (h.after ? "rightMargin" : "leftMargin")
                value: h.fills ? h.slide : 0
                when: h.moving && h.size > 0 && root.widgetsShrink
                restoreMode: Binding.RestoreBindingOrValue
            }
            // ...while a widget that gives up its space shrinks.
            readonly property bool shrinking: h.moving && !h.fills && h.size > 0 && root.widgetsShrink
            property Binding b7: Binding {
                target: h.item ? h.item.Layout : null
                property: root.vertical ? "maximumHeight" : "maximumWidth"
                value: h.size * h.factor
                when: h.shrinking
                restoreMode: Binding.RestoreBinding
            }
            property Binding b8: Binding {
                target: h.item ? h.item.Layout : null
                property: root.vertical ? "preferredHeight" : "preferredWidth"
                value: h.size * h.factor
                when: h.shrinking
                restoreMode: Binding.RestoreBinding
            }
            property Binding b9: Binding {
                target: h.item ? h.item.Layout : null
                property: root.vertical ? "minimumHeight" : "minimumWidth"
                value: 0
                when: h.shrinking
                restoreMode: Binding.RestoreBinding
            }

            // A hidden program asks for attention: open up.
            property Connections attention: Connections {
                target: h.item && h.item.applet ? h.item.applet.plasmoid : null
                function onStatusChanged() {
                    if (root.cfg.openOnAttention && root.cfg.closed && !root.cfg.paused
                            && h.item.applet.plasmoid.status === PlasmaCore.Types.NeedsAttentionStatus)
                        root.cfg.closed = false;
                }
            }
        }
    }

    // --- task managers: icon by icon ----------------------------------------------
    // A task manager is not hidden as a whole: each of its icons is, so that they can slide
    // away smoothly, one after the other if wanted, and so that in "pinned" mode the open
    // programs simply stay. The icons are the children of the task manager's "taskList";
    // each has its model entry (IsLauncher: pinned and not running).

    property var taskHiders: []          // [{item, hider}]
    property int tasksMovingCount: 0
    readonly property bool tasksMoving: tasksMovingCount > 0 || settle.running
    Timer { id: settle; interval: 60 }   // bridges the gap between two icons of a cascade
    Timer { id: taskSync; interval: 30; onTriggered: root.syncTaskHiders() }
    onTaskManagersChanged: taskSync.restart()

    function taskItems() {
        var found = [];
        taskManagers.forEach(s => {
            var list = null;
            try { list = s.item.applet.taskList; } catch (e) {}
            if (!list) return;
            for (var i = 0; i < list.children.length; i++) {
                var c = list.children[i];
                if (c && c.model !== undefined && c.isWindow !== undefined)
                    found.push({item: c, after: s.pos > ownPos});
            }
        });
        return found;
    }
    function syncTaskHiders() {
        var wanted = taskItems(), kept = [];
        taskHiders.forEach(h => {
            if (wanted.some(w => w.item === h.item)) kept.push(h);
            else h.hider.destroy();   // lets go of the icon first, see release()
        });
        wanted.forEach(w => {
            if (!kept.some(h => h.item === w.item))
                kept.push({item: w.item, hider: taskHiderComponent.createObject(
                    root, {task: w.item, after: w.after})});
        });
        taskHiders = kept;
        countOwn();
        listTasks.restart();
    }
    // The programs you chose to keep in the panel, by their application id.
    readonly property var keepIds: Array.from(cfg.taskKeep || []).map(String)
    // With some programs kept in the panel, the mark on the arrow counts the icons that are
    // really in the drawer.
    property int ownWindows: 0
    function countOwn() {
        var n = 0;
        taskHiders.forEach(h => { if (h.hider && h.hider.takesPart && !h.hider.launcherOnly) n++; });
        ownWindows = n;
    }
    // For Tidy's settings window: which programs the task manager shows, so that you can
    // choose per program. Written only when the list changes.
    Timer { id: listTasks; interval: 2000; onTriggered: root.writeTaskList() }
    function writeTaskList() {
        var along = t => vertical ? t.y : t.x, seen = {}, list = [];
        taskHiders.slice().sort((a, b) => along(a.item) - along(b.item)).forEach(h => {
            var m = null;
            try { m = h.item.model; } catch (e) {}
            if (!m || !m.AppId) return;
            var id = String(m.AppId);
            if (seen[id]) return;
            seen[id] = true;
            list.push({id: id, name: String(m.AppName || m.display || id)});
        });
        // A program that is not there right now keeps its place in the list while it is kept.
        var old = [];
        try { old = JSON.parse(cfg.taskList || "[]") || []; } catch (e) { old = []; }
        old.forEach(o => {
            if (o && o.id && !seen[o.id] && keepIds.indexOf(String(o.id)) >= 0) list.push(o);
        });
        var text = JSON.stringify(list);
        if (text === cfg.taskList || !list.length) return;
        cfg.taskList = text;
        persist(cfg);
    }
    // In a cascade the icons go one after the other: closing, the one furthest from the
    // arrow first; opening, the nearest first.
    function cascadeDelay(hider) {
        if (cfg.animation !== "cascade" || !hider.task) return 0;
        var along = t => vertical ? t.y : t.x;
        var mine = along(hider.task), before = 0;
        taskHiders.forEach(h => {
            if (h.hider === hider || !h.hider.takesPart || !h.item) return;
            var nearer = hider.after ? along(h.item) < mine : along(h.item) > mine;
            if (hider.hideMe ? !nearer : nearer) before++;
        });
        return Math.round(before * (moveTime + cfg.animationDuration * 0.4));
    }
    readonly property real someTaskSize: {
        for (var i = 0; i < taskHiders.length; i++)
            if (taskHiders[i].hider.size > 0) return taskHiders[i].hider.size;
        return Kirigami.Units.iconSizes.large;
    }
    onTasksMovingChanged: {
        if (tasksMoving) return;
        // The task manager animates its icons when they move; that is switched off while we
        // move them. Tell it where they are now, or it would animate from the old place later.
        taskHiders.forEach(h => {
            try { h.item.oldX = h.item.x; h.item.oldY = h.item.y; } catch (e) {}
        });
    }

    // Sliding. All icons move together, at their normal size: the ones that go slide out of
    // the task manager's edge and the others close up. The row itself only changes at the
    // start (opening) or the end (closing); in between every icon is drawn shifted by its
    // "shift" times how far the drawer is from open.
    property real slideP: 1            // 0 = closed, 1 = open
    property bool slideActive: false
    property bool slideBusy: false     // from before the row changes until after: no animation of the task manager's own
    property bool slideOpening: false
    property var slideSet: []          // the hiders of the icons that come or go
    property real knobTravel: 0        // how far the arrow travels, when it stands after them
    Timer { id: slideKick; interval: 0; onTriggered: root.runSlide() }
    NumberAnimation {
        id: slideAnim
        target: root; property: "slideP"
        duration: root.cfg.animationDuration; easing.type: Easing.InOutCubic
        onFinished: root.finishSlide()
    }
    function settleTasks() {
        taskHiders.forEach(e => {
            try { e.item.oldX = e.item.x; e.item.oldY = e.item.y; } catch (err) {}
        });
    }
    function finishSlide() {
        if (!slideActive) return;
        slideAnim.stop();
        slideSet.forEach(h => {
            h.factor = slideOpening ? 1 : 0;
            if (!slideOpening) h.present = false;
            h.sliding = false;
        });
        if (!slideOpening) polishTasks();   // the row closes up in the same frame the shifts end
        slideActive = false;
        taskHiders.forEach(e => { e.hider.unshift(); });
        knobTravel = 0;
        slideSet = [];
        settleTasks();
        slideBusy = false;
    }
    function runSlide() {
        if (slideActive) finishSlide();
        var show = [], hide = [];
        taskHiders.forEach(e => {
            var h = e.hider;
            if (!h.task) return;
            if (h.hideMe && h.present) hide.push(h);
            else if (!h.hideMe && (!h.present || h.factor < 1)) show.push(h);
        });
        if (!show.length && !hide.length) return;
        slideBusy = true;
        if ((show.length && hide.length) || !slides || leaving) {
            // Some come while others go (a setting changed): no show, just do it.
            show.forEach(h => { h.present = true; h.factor = 1; });
            hide.forEach(h => { h.factor = 0; h.present = false; });
            polishTasks();
            settleTasks();
            slideBusy = false;
            return;
        }
        slideOpening = show.length > 0;
        slideSet = slideOpening ? show : hide;
        slideSet.forEach(h => { h.sliding = true; });
        if (slideOpening) {
            slideSet.forEach(h => { h.present = true; });
            polishTasks();   // the row opens now; the shifts below put everything back where it was
        }
        // How far each icon is from its place in the closed row. Icons that go slide as one
        // block with the icons after them: by the width of the whole run they are in.
        var along = i => vertical ? i.y : i.x, size = i => vertical ? i.height : i.width;
        var rows = [];
        taskHiders.forEach(e => {
            if (!e.hider.task || !e.hider.present) return;
            var row = rows.find(r => r.list === e.item.parent);
            if (!row) rows.push(row = {list: e.item.parent, hiders: []});
            row.hiders.push(e.hider);
        });
        knobTravel = 0;
        rows.forEach(row => {
            row.hiders.sort((a, b) => along(a.task) - along(b.task));
            var total = 0, i = 0;
            while (i < row.hiders.length) {
                if (!row.hiders[i].sliding) { row.hiders[i].shift = total; i++; continue; }
                var end = i;
                while (end < row.hiders.length && row.hiders[end].sliding) { total += size(row.hiders[end].task); end++; }
                for (; i < end; i++) row.hiders[i].shift = total;
            }
            if (row.hiders.length && !row.hiders[0].after) knobTravel += total;
        });
        slideP = slideOpening ? 0 : 1;
        slideActive = true;
        slideAnim.from = slideP;
        slideAnim.to = slideOpening ? 1 : 0;
        slideAnim.restart();
    }

    Component {
        id: taskHiderComponent
        QtObject {
            id: th
            property Item task: null
            property bool after: true
            readonly property bool launcherOnly: task && task.model ? task.model.IsLauncher === true : false
            // Does this icon go into the drawer at all, and should it be hidden now?
            // A program you chose to keep in the panel stays out of the drawer.
            readonly property bool kept: task && task.model
                ? root.keepIds.indexOf(String(task.model.AppId)) >= 0 : false
            readonly property bool takesPart: task !== null && !kept
                && (root.cfg.taskMode === "all" || (root.cfg.taskMode === "pinned" && launcherOnly))
            onTakesPartChanged: root.countOwn()
            onLauncherOnlyChanged: root.countOwn()
            readonly property bool hideMe: root.wantClosed && takesPart
            property real size: 0     // natural size, remembered while visible
            readonly property real naturalSize: size > 0 ? size : root.someTaskSize
            // Two things make an icon come and go: its place in the row ("present") and how
            // see-through it is ("factor"). Sliding ties them together: the place gets
            // narrower as the icon fades. Fading and one-by-one keep the icon at its normal
            // size: opening, its place opens first and the neighbours make room, then it
            // fades in; closing, it fades out and then gives up its place.
            property real factor: 1
            property bool present: true
            property int delay: 0
            property bool ready: false
            readonly property bool moving: factor > 0 && factor < 1
            // Sliding: is this icon one of those that come or go, and how far is it shifted.
            property bool sliding: false
            property real shift: 0
            property var mover: null   // the icon's own "translate", which draws it shifted
            readonly property real seen: (root.slideActive && sliding) ? Math.min(1, root.slideP * 1.5) : factor

            function measure() {
                if (task && factor === 1 && !root.tasksMoving)
                    size = root.vertical ? task.height : task.width;
            }
            function apply() {
                appear.stop();
                vanish.stop();
                if (!ready || root.leaving) {
                    present = !hideMe;
                    factor = hideMe ? 0 : 1;
                    return;
                }
                if (root.slides) {
                    slideKick.restart();   // all icons together, see runSlide()
                    return;
                }
                delay = root.cascadeDelay(th);
                settle.restart();
                if (root.shrinks) factor = hideMe ? 0 : 1;   // the Behavior below animates it
                else if (hideMe) vanish.start();
                else appear.start();
            }
            onHideMeChanged: apply()
            onMovingChanged: root.tasksMovingCount += moving ? 1 : -1
            onFactorChanged: {
                if (root.shrinks) present = factor > 0;
                // Fully back: tell the task manager where the icon is, so that it does not
                // animate it from an old place the next time something moves.
                if (factor === 1 && task) {
                    try { task.oldX = task.x; task.oldY = task.y; } catch (e) {}
                }
            }
            Component.onCompleted: {
                try { mover = task.transform.length ? task.transform[0] : null; } catch (e) {}
                measure();
                apply();
                ready = true;
            }
            // Must let go of the icon before it goes: the bindings only restore while they exist.
            function release() {
                ready = false;
                appear.stop();
                vanish.stop();
                unshift();
                sliding = false;
                present = true;
                factor = 1;
            }
            Component.onDestruction: release()
            property Connections sizes: Connections {
                target: th.task
                function onWidthChanged() { th.measure(); }
                function onHeightChanged() { th.measure(); }
            }

            Behavior on factor {
                enabled: th.ready && root.shrinks && !root.leaving
                NumberAnimation { duration: root.cfg.animationDuration; easing.type: Easing.InOutCubic }
            }
            property SequentialAnimation appear: SequentialAnimation {
                PauseAnimation { duration: th.delay }
                ScriptAction { script: th.present = true }
                PauseAnimation { duration: root.moveTime }   // the neighbours make room
                NumberAnimation {
                    target: th; property: "factor"; to: 1
                    duration: root.cfg.animationDuration; easing.type: Easing.InOutQuad
                }
            }
            property SequentialAnimation vanish: SequentialAnimation {
                PauseAnimation { duration: th.delay }
                NumberAnimation {
                    target: th; property: "factor"; to: 0
                    duration: root.cfg.animationDuration; easing.type: Easing.InOutQuad
                }
                ScriptAction { script: th.present = false }
            }

            property Binding b1: Binding {
                target: th.task; property: "visible"; value: false
                when: !th.present
                restoreMode: Binding.RestoreBindingOrValue
            }
            property Binding b2: Binding {
                target: th.task; property: "opacity"; value: th.seen
                when: th.seen < 1
                restoreMode: Binding.RestoreBindingOrValue
            }
            // The shift while sliding, on the icon's own "translate" (the one the task manager
            // uses for its move animation, which is off meanwhile).
            property Binding b7: Binding {
                target: th.mover
                property: root.vertical ? "y" : "x"
                value: -th.shift * (1 - root.slideP)
                when: root.slideActive && th.shift !== 0
                restoreMode: Binding.RestoreNone   // put back to zero by hand, see unshift()
            }
            function unshift() {
                shift = 0;
                if (mover) { mover.x = 0; mover.y = 0; }
            }
            // The icon's room in the row. A hidden icon keeps no width either, because the task
            // manager adds up the widths of all its icons.
            readonly property real room: root.shrinks ? naturalSize * factor : (present ? naturalSize : 0)
            readonly property bool holding: factor < 1 || !present
            property Binding b3: Binding {
                target: th.task ? th.task.Layout : null
                property: root.vertical ? "maximumHeight" : "maximumWidth"
                value: th.room
                when: th.holding
                restoreMode: Binding.RestoreBinding
            }
            property Binding b4: Binding {
                target: th.task ? th.task.Layout : null
                property: root.vertical ? "preferredHeight" : "preferredWidth"
                value: th.room
                when: th.holding
                restoreMode: Binding.RestoreBinding
            }
            property Binding b5: Binding {
                target: th.task ? th.task.Layout : null
                property: root.vertical ? "minimumHeight" : "minimumWidth"
                value: 0
                when: th.holding
                restoreMode: Binding.RestoreBinding
            }
            property Binding b6: Binding {
                target: th.task; property: "clip"; value: true
                when: th.moving && root.shrinks
                restoreMode: Binding.RestoreBindingOrValue
            }
            // The task manager animates an icon whenever it changes place; "completed" is its
            // switch for that. Off for every icon while we slide them ourselves, and off for
            // an icon that is hidden or fading: it must not fly in from where it last was.
            property Binding b8: Binding {
                target: th.task; property: "completed"; value: false
                when: (root.tasksMoving && root.shrinks) || root.slideActive || root.slideBusy
                      || (!root.shrinks && th.holding)
                restoreMode: Binding.RestoreBindingOrValue
            }
        }
    }

    // Per task manager in the drawer: notice icons coming and going, where the open programs
    // stand, and a program that asks for attention.
    Instantiator {
        id: managers
        model: root.taskManagers
        delegate: QtObject {
            id: tm
            required property var modelData
            readonly property var applet: modelData && modelData.item ? modelData.item.applet : null
            readonly property var tasksModel: applet && applet.tasksModel !== undefined ? applet.tasksModel : null
            property bool live: true
            function release() { live = false; }
            Component.onDestruction: release()
            readonly property bool arranging: live && !root.leaving && !root.cfg.paused
            property Connections icons: Connections {
                target: tm.applet && tm.applet.taskList !== undefined ? tm.applet.taskList : null
                function onChildrenChanged() { taskSync.restart(); }
            }
            // Icons that slide out go out of sight at the edge of the row.
            property Binding clip: Binding {
                target: tm.applet && tm.applet.taskList !== undefined ? tm.applet.taskList : null
                property: "clip"; value: true
                when: root.slideActive
                restoreMode: Binding.RestoreBindingOrValue
            }
            // Where the open programs stand: on their pinned spot (the task manager's own way),
            // or all together before or after the pinned programs. For that the task manager
            // must stop putting a running pinned program on its pinned spot ("launchInPlace")
            // and allow pinned and open programs to mix ("separateLaunchers" off); then the
            // open ones are moved to the front or the back.
            readonly property bool ordering: arranging && root.cfg.activePlace !== "fixed"
            property Binding b1: Binding {
                target: tm.tasksModel; property: "launchInPlace"; value: false
                when: tm.ordering
                restoreMode: Binding.RestoreBinding
            }
            property Binding b2: Binding {
                target: tm.tasksModel; property: "separateLaunchers"; value: false
                when: tm.ordering
                restoreMode: Binding.RestoreBinding
            }
            readonly property string order: ordering ? root.cfg.activePlace : ""
            onOrderChanged: arrange.restart()
            function isOpen(model, row) {
                return !model.data(model.makeModelIndex(row), TaskManager.AbstractTasksModel.IsLauncher);
            }
            function arrangeOpen() {
                var model = tm.tasksModel;
                if (!ordering || !model) return;
                var row, spot;
                if (root.cfg.activePlace === "start") {
                    for (row = 0, spot = 0; row < model.count; row++) {
                        if (!isOpen(model, row)) continue;
                        if (row !== spot) model.move(row, spot);
                        spot++;
                    }
                } else {
                    for (row = model.count - 1, spot = model.count - 1; row >= 0; row--) {
                        if (!isOpen(model, row)) continue;
                        if (row !== spot) model.move(row, spot);
                        spot--;
                    }
                }
            }
            property Timer arrange: Timer { interval: 60; onTriggered: tm.arrangeOpen() }
            property Connections rows: Connections {
                target: tm.ordering ? tm.tasksModel : null
                function onRowsInserted() { tm.arrange.restart(); }
                function onRowsRemoved() { tm.arrange.restart(); }
                function onDataChanged() { tm.arrange.restart(); }
            }
            property Connections attention: Connections {
                target: tm.applet ? tm.applet.plasmoid : null
                function onStatusChanged() {
                    if (root.cfg.openOnAttention && root.cfg.closed && !root.cfg.paused
                            && root.cfg.taskMode === "all"
                            && tm.applet.plasmoid.status === PlasmaCore.Types.NeedsAttentionStatus)
                        root.cfg.closed = false;
                }
            }
        }
    }

    // --- task manager: the pinned list (older versions) -----------------------------
    // Older versions emptied the task manager's list of pinned programs. Nothing is taken
    // any more; this only hands a list back that such a version still holds.
    // The pinned icons are a list in the task manager's settings. Closed: remember the list
    // and empty it; programs that are running stay, they are windows. Open: put it back,
    // keeping anything that was pinned in the meantime.

    // What the drawer has taken from a task manager is kept in its own settings, so that it
    // survives a restart. Settings written from here reach Plasma's configuration a moment
    // later, and when Tidy changes a setting in that moment Plasma reloads them all, without
    // ours. So every change is written out at once, and a copy in memory wins over whatever
    // a reload brings back.
    property var savedMemory: ({})
    function persist(map) {
        try { map.writeConfig(); } catch (e) {}
    }
    function loadSaved(key) {
        if (!(key in savedMemory)) {
            var value = {};
            try { value = JSON.parse(cfg[key] || "{}") || {}; } catch (e) { value = {}; }
            savedMemory[key] = value;
        }
        return savedMemory[key];
    }
    function storeSaved(key, value) {
        savedMemory[key] = value;
        var text = JSON.stringify(value);
        if (cfg[key] !== text) cfg[key] = text;
        persist(cfg);
    }
    function restoreLaunchers(conf, list) {
        Array.from(conf.launchers).forEach(l => { if (list.indexOf(l) < 0) list.push(l); });
        conf.launchers = list;
        persist(conf);
    }

    function syncPinned() {
        var saved = loadSaved("savedLaunchers");
        siblings.forEach(s => {
            if (!isTasks(s.plugin)) return;
            var conf = null;
            try { conf = s.item.applet.plasmoid.configuration; } catch (e) {}
            if (!conf) return;
            // Worked out here rather than taken from pinnedTargets: right after a settings
            // change that list may not have caught up yet.
            var hide = false;
            if (hide && !(s.id in saved)) {
                // Save first, empty afterwards: a crash in between must not lose the list.
                saved[s.id] = Array.from(conf.launchers);
                storeSaved("savedLaunchers", saved);
                conf.launchers = [];
                persist(conf);
            } else if (!hide && (s.id in saved)) {
                restoreLaunchers(conf, saved[s.id]);
                delete saved[s.id];
                storeSaved("savedLaunchers", saved);
            }
        });
    }
    Connections {
        target: root.cfg
        function onClosedChanged() { root.syncPinned(); }
        function onTargetsChanged() { root.syncPinned(); root.syncFill(); }
        function onTaskModeChanged() { root.syncPinned(); }
        function onPlaceChanged() { root.syncFill(); }
        function onPausedChanged() { root.syncPinned(); root.syncFill(); }
        function onDebugChanged() {
            // For testing: opens the widget's own settings.
            if (root.cfg.debug === "configure") Plasmoid.internalAction("configure").trigger();
            // For testing: as if the panel were clicked at this place, "tap:<pixels>".
            if (String(root.cfg.debug).indexOf("tap:") === 0) {
                var at = parseFloat(String(root.cfg.debug).split(":")[1]);
                var before = root.cfg.closed;
                var others = root.anyClosesOnClick();
                root.panelTapped(at);
                Qt.callLater(() => console.warn("TIDYTAP " + JSON.stringify({id: Plasmoid.id,
                    at: at, empty: root.isEmptySpot(at), opens: root.cfg.openOnPanelClick,
                    closes: root.cfg.closeOnPanelClick, anyCloses: others,
                    before: before, closed: root.cfg.closed})));
            }
        }
        // A reload from outside brought back an older version: ours wins.
        function onSavedLaunchersChanged() {
            if ("savedLaunchers" in root.savedMemory)
                root.storeSaved("savedLaunchers", root.savedMemory["savedLaunchers"]);
        }
        function onSavedFillChanged() {
            if ("savedFill" in root.savedMemory)
                root.storeSaved("savedFill", root.savedMemory["savedFill"]);
        }
    }
    // Removed from the panel (or Plasma shutting down): never leave a task manager without
    // its pinned icons. At the next start a closed drawer empties the list again.
    Component.onDestruction: {
        for (var i = 0; i < hiders.count; i++) {
            var hider = hiders.objectAt(i);
            if (hider) hider.release();
        }
        finishSlide();
        taskHiders.forEach(h => { try { h.hider.release(); } catch (e) {} });
        for (var j = 0; j < managers.count; j++) {
            var manager = managers.objectAt(j);
            if (manager) manager.release();
        }
        leaving = true;
        syncFill();
        var saved = loadSaved("savedLaunchers");
        siblings.forEach(s => {
            if (!(s.id in saved)) return;
            try {
                restoreLaunchers(s.item.applet.plasmoid.configuration, saved[s.id]);
                delete saved[s.id];
            } catch (e) {}
        });
        storeSaved("savedLaunchers", saved);
    }

    // --- arrow after a task manager that fills the panel --------------------------
    // Placed after its items, the arrow would end up at the far end of the task manager's
    // empty space. So the task manager stops filling the panel and this widget fills it
    // instead: the arrow sits right behind the last program and the rest of our width is
    // empty panel. The task manager's own setting is put back when this no longer applies.

    property bool stretching: false
    function syncFill() {
        var saved = loadSaved("savedFill");
        var before = JSON.stringify(saved), present = {};
        siblings.forEach(s => {
            if (!isTasks(s.plugin)) return;
            present[s.id] = true;
            var conf = null;
            try { conf = s.item.applet.plasmoid.configuration; } catch (e) {}
            if (!conf) return;
            var take = cfg.place === "after" && !leaving && !cfg.paused && inTargets(s.id)
                       && s.pos < ownPos;
            if (take && !(s.id in saved)) {
                if (conf.fill === false) return;   // already set that way by the user
                // Save first, change afterwards: a crash in between must not lose the setting.
                saved[s.id] = true;
                storeSaved("savedFill", saved);
                conf.fill = false;
                persist(conf);
            } else if (!take && (s.id in saved)) {
                conf.fill = true;
                persist(conf);
                delete saved[s.id];
            }
        });
        // Only once the list of widgets is known: a task manager that is gone needs no entry.
        if (siblings.length > 0)
            Object.keys(saved).forEach(id => { if (!(id in present)) delete saved[id]; });
        if (JSON.stringify(saved) !== before) storeSaved("savedFill", saved);
        stretching = Object.keys(saved).length > 0;
    }

    // --- a mark on the closed drawer ----------------------------------------------
    // When the drawer hides a task manager with everything in it, a mark on the arrow tells
    // that programs are open in there, or that one asks for attention. The windows are
    // counted with a model of our own, set up like the hidden task manager.

    readonly property var hiddenTasks: cfg.taskMode === "all" ? taskManagers : []
    readonly property var hiddenTasksConf: {
        try { return hiddenTasks.length ? hiddenTasks[0].item.applet.plasmoid.configuration : null; }
        catch (e) { return null; }
    }
    Loader {
        id: counter
        active: root.cfg.indicator !== "none" && root.hiddenTasks.length > 0
        sourceComponent: Item {
            readonly property int windows: tasksModel.count
            readonly property bool attention: tasksModel.anyTaskDemandsAttention
            TaskManager.VirtualDesktopInfo { id: desktopInfo }
            TaskManager.ActivityInfo { id: activityInfo }
            TaskManager.TasksModel {
                id: tasksModel
                virtualDesktop: desktopInfo.currentDesktop
                activity: activityInfo.currentActivity
                filterByVirtualDesktop: root.hiddenTasksConf ? root.hiddenTasksConf.showOnlyCurrentDesktop : false
                filterByActivity: root.hiddenTasksConf ? root.hiddenTasksConf.showOnlyCurrentActivity : true
                filterNotMinimized: root.hiddenTasksConf ? root.hiddenTasksConf.showOnlyMinimized : false
                groupMode: TaskManager.TasksModel.GroupDisabled
            }
        }
    }
    readonly property int hiddenWindows: !counter.item ? 0
        : (keepIds.length ? ownWindows : counter.item.windows)
    readonly property bool hiddenAttention: counter.item ? counter.item.attention : false
    readonly property bool markShown: wantClosed && counter.item !== null
        && (hiddenAttention || (cfg.indicator !== "attention" && hiddenWindows > 0))

    // --- close when a window fills the screen ------------------------------------------

    Loader {
        active: root.cfg.closeOnMaximized
        sourceComponent: Item {
            id: watch
            property string last: ""
            function evaluate() {
                var index = windows.activeTask, state = "other";
                if (index.valid && (windows.data(index, TaskManager.AbstractTasksModel.IsMaximized)
                                    || windows.data(index, TaskManager.AbstractTasksModel.IsFullScreen)))
                    state = "big:" + String(windows.data(index, TaskManager.AbstractTasksModel.WinIdList));
                if (state === last) return;
                var first = last === "";
                last = state;
                // At the moment a window that fills the screen comes to the front, or the window
                // in front starts filling it; after that the arrow works as usual.
                if (!first && state !== "other" && !root.cfg.paused && !root.cfg.closed)
                    root.cfg.closed = true;
            }
            TaskManager.VirtualDesktopInfo { id: watchDesktop }
            TaskManager.ActivityInfo { id: watchActivity }
            TaskManager.TasksModel {
                id: windows
                virtualDesktop: watchDesktop.currentDesktop
                activity: watchActivity.currentActivity
                filterByVirtualDesktop: true
                filterByActivity: true
                groupMode: TaskManager.TasksModel.GroupDisabled
                onActiveTaskChanged: check.restart()
                onDataChanged: check.restart()
            }
            Timer { id: check; interval: 150; onTriggered: watch.evaluate() }
            Component.onCompleted: check.restart()
        }
    }

    // --- opening and closing ---------------------------------------------------

    function toggle() { cfg.closed = !cfg.closed; }
    // The widget's own keyboard shortcut (set in Tidy, or in Plasma's settings of the widget).
    activationTogglesExpanded: false
    Connections {
        target: Plasmoid
        function onActivated() {
            if (root.cfg.paused) root.cfg.paused = false;
            else root.toggle();
        }
    }

    // Where is the pointer? Over the panel is watched on the panel's layout; over the
    // drawer itself means over the arrow or over one of its widgets.
    Component { id: hoverComponent; HoverHandler {} }
    property var panelHover: null
    onContainerChanged: {
        // The old one may be gone already, together with the panel it was watching.
        try { if (panelHover) panelHover.destroy(); } catch (e) {}
        try { if (panelTap) panelTap.destroy(); } catch (e) {}
        panelHover = null;
        panelTap = null;
        if (container && container.parent) {
            panelHover = hoverComponent.createObject(container.parent);
            panelTap = tapComponent.createObject(container.parent);
        }
    }

    // A click on an empty spot of the panel closes the drawer. The panel passes every
    // click to this handler as well, also those on a widget, so "empty" is worked out
    // from the layout: no widget there, or only the unused part of one that fills the panel.
    Component {
        id: tapComponent
        TapHandler {
            acceptedButtons: Qt.LeftButton
            onTapped: (eventPoint, button) => root.panelTapped(
                root.vertical ? eventPoint.position.y : eventPoint.position.x)
        }
    }
    property var panelTap: null
    // Every drawer in the panel hears the same click. Together they do one thing: if a
    // drawer that closes on such a click is open, the click closes; only when none is, it
    // opens the drawers that are set to open that way. Each drawer decides from how things
    // are at the moment of the click and acts a moment later, so that one drawer closing
    // does not make the next one think nothing was open.
    function closesOnClick(conf) {
        return !conf.closed && !conf.paused && conf.closeOnPanelClick;
    }
    function anyClosesOnClick() {
        if (closesOnClick(cfg)) return true;
        for (var i = 0; i < siblings.length; i++) {
            if (siblings[i].plugin !== Plasmoid.pluginName) continue;
            try {
                if (closesOnClick(siblings[i].item.applet.plasmoid.configuration)) return true;
            } catch (e) {}
        }
        return false;
    }
    function panelTapped(pos) {
        if (cfg.paused) return;
        if (cfg.closed) {
            if (cfg.openOnPanelClick && isEmptySpot(pos) && !anyClosesOnClick())
                Qt.callLater(() => { root.cfg.closed = false; });
            return;
        }
        if (cfg.closeOnPanelClick && isEmptySpot(pos))
            Qt.callLater(() => { root.cfg.closed = true; });
        else if (cfg.closeAfterUse && inDrawerItem(pos))
            useTimer.restart();
    }
    // A click on something in the drawer: close once it has done its work. A pop-up that the
    // click opened (system tray) is waited for.
    function inDrawerItem(pos) {
        var mirrored = !vertical && Qt.application.layoutDirection === Qt.RightToLeft;
        return drawerItems.some(s => {
            var k = s.item;
            if (!k || !k.applet || !k.visible || k.opacity === 0) return false;
            var start = vertical ? k.y : k.x, full = vertical ? k.height : k.width;
            var extent = contentExtent(k);
            var from = mirrored ? start + full - extent : start;
            return pos >= from && pos <= from + extent;
        });
    }
    property bool closeAfterPopup: false
    Timer {
        id: useTimer
        interval: 400
        onTriggered: {
            if (root.popupOpen) root.closeAfterPopup = true;
            else if (!root.cfg.paused) root.cfg.closed = true;
        }
    }
    onPopupOpenChanged: {
        if (!popupOpen && closeAfterPopup) {
            closeAfterPopup = false;
            if (!cfg.paused) cfg.closed = true;
        }
    }
    function contentExtent(k) {
        var full = vertical ? k.height : k.width;
        var wanted = vertical ? k.applet.Layout.preferredHeight : k.applet.Layout.preferredWidth;
        return (wanted > 0 && wanted < full) ? wanted : full;
    }
    function isEmptySpot(pos) {
        if (!container || !container.parent) return false;
        var kids = container.parent.children;
        var mirrored = !vertical && Qt.application.layoutDirection === Qt.RightToLeft;
        for (var i = 0; i < kids.length; i++) {
            var k = kids[i];
            // Hidden by a drawer but still holding its place: that looks empty too.
            if (!k || !k.isAppletContainer || !k.applet || !k.visible || k.opacity === 0) continue;
            var plugin = "";
            try { plugin = k.applet.plasmoid.pluginName; } catch (e) {}
            if (plugin === "org.kde.plasma.panelspacer" || plugin === "org.kde.plasma.marginsseparator")
                continue;
            var start = vertical ? k.y : k.x, full = vertical ? k.height : k.width;
            var extent = contentExtent(k);
            var from = mirrored ? start + full - extent : start;
            if (pos >= from && pos <= from + extent) return false;
        }
        return true;
    }
    readonly property bool pointerInPanel: (panelHover ? panelHover.hovered : false) || arrowHovered

    readonly property var drawerItems: siblings.filter(s => inTargets(s.id))
    property bool itemsHovered: false
    function updateItemsHovered() {
        var any = false;
        for (var i = 0; i < watchers.count; i++) {
            var w = watchers.objectAt(i);
            if (w && w.inside) { any = true; break; }
        }
        itemsHovered = any;
    }
    Instantiator {
        id: watchers
        model: root.drawerItems
        onObjectAdded: root.updateItemsHovered()
        onObjectRemoved: root.updateItemsHovered()
        delegate: QtObject {
            id: watcher
            required property var modelData
            readonly property Item item: modelData ? modelData.item : null
            property var handler: null
            // A widget that fills the panel is mostly empty space: only the part that holds
            // its contents counts as the drawer.
            readonly property real extent: {
                if (!item || !item.applet) return 0;
                var full = root.vertical ? item.height : item.width;
                var wanted = root.vertical ? item.applet.Layout.preferredHeight
                                           : item.applet.Layout.preferredWidth;
                return (wanted > 0 && wanted < full) ? wanted : full;
            }
            readonly property bool inside: {
                if (!handler || !handler.hovered || !item) return false;
                var pos = root.vertical ? handler.point.position.y : handler.point.position.x;
                var full = root.vertical ? item.height : item.width;
                var mirrored = !root.vertical && Qt.application.layoutDirection === Qt.RightToLeft;
                return mirrored ? pos >= full - extent : pos <= extent;
            }
            onInsideChanged: root.updateItemsHovered()
            Component.onCompleted: if (item) handler = hoverComponent.createObject(item)
            Component.onDestruction: { try { if (handler) handler.destroy(); } catch (e) {} }
        }
    }
    readonly property bool pointerInDrawer: arrowHovered || itemsHovered
    readonly property bool pointerHere: cfg.closeScope === "panel" ? pointerInPanel : pointerInDrawer
    function hasPopupOpen(applet) {
        // Widgets shown in full in the panel (task manager, pager, ...) always count as
        // "expanded"; only a widget with an icon in the panel has a real pop-up.
        return applet && applet.expanded && applet.compactRepresentationItem !== null
            && applet.compactRepresentationItem.visible;
    }
    // A pop-up of one of the widgets (menu, calendar, ...) counts as "still busy here".
    readonly property bool popupOpen: siblings.some(
        s => hasPopupOpen(s.item.applet) || (s.tray !== null && s.tray.expanded))

    Timer {
        id: closeTimer
        interval: Math.max(0, root.cfg.closeDelay)
        running: root.cfg.autoClose && !root.cfg.closed && !root.cfg.paused && !root.editing
                 && !root.pointerHere && !root.popupOpen
                 && (root.cfg.closeScope !== "panel" || root.panelHover !== null)
        onTriggered: root.cfg.closed = true
    }
    Timer {
        id: hoverTimer
        interval: Math.max(0, root.cfg.hoverDelay)
        onTriggered: if (root.arrowHovered) root.cfg.closed = false
    }

    P5Support.DataSource {
        id: runner
        engine: "executable"
        onNewData: (source, data) => disconnectSource(source)
    }
    Plasmoid.contextualActions: [
        PlasmaCore.Action {
            text: root.cfg.textSettings
            icon.name: "configure"
            visible: root.cfg.tidyCommand !== ""
            onTriggered: runner.connectSource(root.cfg.tidyCommand + " --settings")
        }
    ]

    // --- the arrow -------------------------------------------------------------

    preferredRepresentation: fullRepresentation
    Plasmoid.backgroundHints: PlasmaCore.Types.NoBackground

    readonly property int thickness: Kirigami.Units.iconSizes.small + Kirigami.Units.smallSpacing
    Layout.fillWidth: !vertical && stretching
    Layout.fillHeight: vertical && stretching
    Layout.minimumWidth: vertical ? -1 : thickness
    Layout.preferredWidth: vertical ? -1 : thickness
    Layout.maximumWidth: vertical ? -1 : (stretching ? Infinity : thickness)
    Layout.minimumHeight: vertical ? thickness : -1
    Layout.preferredHeight: vertical ? thickness : -1
    Layout.maximumHeight: vertical ? (stretching ? Infinity : thickness) : -1

    // Closed, the arrow points the way the drawer opens: away from the nearest end of the
    // panel. Open, it points back.
    readonly property bool inFirstHalf: {
        if (!container || !container.parent) return true;
        var at = (vertical ? container.y : container.x) + thickness / 2;
        return at < (vertical ? container.parent.height : container.parent.width) / 2;
    }
    readonly property bool pointsForward: (cfg.closed === inFirstHalf) !== cfg.reverseArrow
    readonly property string arrowIcon: {
        var f = pointsForward;
        switch (cfg.icon) {
        case "double":
            return vertical ? (f ? "arrow-down-double" : "arrow-up-double")
                            : (f ? "arrow-right-double" : "arrow-left-double");
        case "triangle":
            return vertical ? (f ? "pan-down-symbolic" : "pan-up-symbolic")
                            : (f ? "pan-end-symbolic" : "pan-start-symbolic");
        case "dots": return vertical ? "view-more-symbolic" : "view-more-horizontal-symbolic";
        case "menu": return "application-menu";
        case "handle": return "drag-handle-symbolic";
        case "custom": return cfg.iconCustom;
        case "none": return "";
        }
        return vertical ? (f ? "arrow-down" : "arrow-up") : (f ? "arrow-right" : "arrow-left");
    }

    property bool arrowHovered: false

    fullRepresentation: Item {
        // The arrow sits at the start of the widget; when the widget fills the panel, the
        // rest of it is empty panel space.
        PlasmaCore.ToolTipArea {
            width: root.vertical ? parent.width : root.thickness
            height: root.vertical ? root.thickness : parent.height
            // Standing after the icons, the arrow slides along with them.
            readonly property real travel: root.slideActive ? -root.knobTravel * (1 - root.slideP) : 0
            x: root.vertical ? 0 : travel
            y: root.vertical ? travel : 0
            readonly property string action: root.cfg.paused ? root.cfg.textPaused
                : (root.cfg.closed ? root.cfg.textOpen : root.cfg.textClose)
            // With a name: the name, and below it what a click does.
            mainText: root.cfg.name !== "" ? root.cfg.name : action
            subText: root.cfg.name !== "" ? action : ""

            Kirigami.Icon {
                anchors.centerIn: parent
                width: Kirigami.Units.iconSizes.small
                height: width
                id: arrow
                source: root.arrowIcon
                visible: root.cfg.icon !== "none"
                active: root.arrowHovered
                opacity: root.cfg.paused ? 0.4 : 1
            }
            // Without an icon the spot only shows itself under the pointer.
            Rectangle {
                anchors.fill: parent
                anchors.margins: Math.round(Kirigami.Units.smallSpacing / 2)
                visible: root.cfg.icon === "none" && root.arrowHovered
                radius: Kirigami.Units.smallSpacing
                color: Kirigami.Theme.textColor
                opacity: 0.15
            }
            // The mark: a dot, or the number of open programs.
            Rectangle {
                id: mark
                readonly property bool counting: root.cfg.indicator === "count" && root.hiddenWindows > 0
                visible: root.markShown
                anchors.horizontalCenter: arrow.right
                anchors.horizontalCenterOffset: -Math.round(arrow.width * 0.15)
                anchors.verticalCenter: arrow.top
                anchors.verticalCenterOffset: Math.round(arrow.height * 0.1)
                height: Math.round(arrow.height * (counting ? 0.7 : 0.4))
                width: counting ? Math.max(height, number.implicitWidth + Math.round(height * 0.5)) : height
                radius: height / 2
                color: root.hiddenAttention ? Kirigami.Theme.neutralTextColor : Kirigami.Theme.highlightColor
                Text {
                    id: number
                    visible: mark.counting
                    anchors.centerIn: parent
                    text: root.hiddenWindows
                    color: Kirigami.Theme.highlightedTextColor
                    font.pixelSize: Math.round(mark.height * 0.8)
                    font.bold: true
                }
            }
            MouseArea {
                anchors.fill: parent
                hoverEnabled: true
                acceptedButtons: Qt.LeftButton
                onContainsMouseChanged: root.arrowHovered = containsMouse
                onClicked: {
                    hoverTimer.stop();
                    if (root.cfg.paused) root.cfg.paused = false;
                    else root.toggle();
                }
                onEntered: if (root.cfg.openOn === "hover" && root.cfg.closed && !root.cfg.paused)
                               hoverTimer.restart()
                onExited: hoverTimer.stop()
            }
        }
    }
}
